
spring:
  application:
    name: tlias-web-management
  #数据库连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: JDBC:mysql://localhost:3306/tlias
    username: root
    password: 20060614
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 10MB
      #最大请求大小（包括所有文件和表单数据的最大大小）
      max-request-size: 100MB
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #打印日志
    #开启了驼峰映射命名的开关
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#阿里云oss配置
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-ai-wlf0614
    region: cn-beijing
    #冒号后面要跟一个空格

